### PR TITLE
Use protocol relative url

### PR DESCRIPTION
**Pull request by nyushi**
I'm getting the following browser(chrome) error at https.

```
Mixed Content: The page at 'https://mysite.example.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Lobster'. This request has been blocked; the content must be served over HTTPS.
```

This patch changes url to protocol relative.

### CODE REVIEW

**Comment by Pingendo** [comment]
fixed. thx.

**Comment by nyushi** [comment]
@Pingendo 

Thanks for your reply, but import link seems not fixed yet.
([bootstrap.css](http://pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css) still contains `@import url("http://fonts.googleapis.com/css?family=Lato|Lato");`.)

Could you change `http://...` to `//...`?

**Comment by Pingendo** [comment]
If we change to `//...` preview from file will not work. Maybe we should include from `https://...` by default.

**Comment by yushi** [comment]
That’s more like it. 
FYI: http://stackoverflow.com/questions/4831741/can-i-change-all-my-http-links-to-just

Thanks.

**Comment by nyushi** [comment]
//Sorry, I wrote in another account. removed.

That’s more like it. 
FYI: http://stackoverflow.com/questions/4831741/can-i-change-all-my-http-links-to-just

Thanks.

**Comment by Pingendo** [comment]
Ok, just changed http:// imports to https:// .

**Pull request closed without merging**
